### PR TITLE
Fixed the way trait projections onto polynomials were being saved 

### PR DESCRIPTION
**Pull request by snafees**
The projections (regressions) of the trait onto the 1st & 2nd order orthogonal polynomials needed to be saved with the trait file prefix to distinguish these from the work done to compute the polynomials.

### CODE REVIEW

**Review by snafees — COMMENTED** [review]
Making sure to not have `naming_phenotype` not defined too many times unnecessarily.

**Review by pranathivemuri — CHANGES_REQUESTED** [review]
looks good! but wondering if there are really 61 files that you are testing?

**Comment by snafees** [comment]
> looks good! but wondering if there are really 61 files that you are testing?

Yes, actually, since we are computing lots of things and want to make sure that each step is done correctly. But yea, there are definitely lots of files!

**Comment by pranathivemuri** [comment]
Please try this instead - https://numpy.org/doc/stable/reference/generated/numpy.savez.html

**Pull request merged**
