### PR TITLE
fixing ubuntu latest issue

### PR DESCRIPTION
**Pull request by snafees**
https://github.com/actions/virtual-environments/issues/1816 as shown here

Many thanks to contributing to snafees/ortho_seqs!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Ensure the test suite passes with [pytest](https://docs.pytest.org/en/latest/) . (command to run: `pytest` or `make coverage` if you want to see which lines don't have tests yet)
 - [ ] Make sure your code is linted and autoformatted using [black](https://github.com/psf/black) (`black . --check`).
 - [ ] Documentation in `usage.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Review by pranathivemuri — APPROVED** [review]

**Comment by pranathivemuri** [comment]
why did you have to make this change again? summarizing and then linking to the issue would be great

**Comment by snafees** [comment]
> why did you have to make this change again? summarizing and then linking to the issue would be great

In an earlier failed deployment, it showed that there was an issue with the ubuntu release. And gave a fix actions/virtual-environments#1816 as shown here

**Comment by pranathivemuri** [comment]
I don't think you are pointing to the right link in the issue. could you please press on the three dots and get the link to the exact comment you are referring to as well as the error you have seen?

**Comment by snafees** [comment]
> I don't think you are pointing to the right link in the issue. could you please press on the three dots and get the link to the exact comment you are referring to as well as link to the error you have seen?

So the error showed up on this deployment a couple of days ago which unfortunately does not show up anymore after I triggered the deployment an hour ago. The error said something about there was an issue with ubuntu latest. What I did is similar to what this [user](https://github.com/actions/virtual-environments/issues/2392) experienced and what he did to solve his issue. 
On that [link](https://github.com/actions/virtual-environments/issues/1816) I posted earlier, here's the part I was referring to: `Switch back to Ubuntu 18.04 by specifying the “ubuntu-18.04” label. We will continue to support Ubuntu 18.04.`

**Comment by pranathivemuri** [comment]
got it feel free to merge this PR. 

For future, you can go and see the previous workflows by going to your repo's main page and clicking actions. It shows all the CI workflows run through github actions - https://github.com/snafees/ortho_seqs/actions.

**Comment by snafees** [comment]
> https://github.com/snafees/ortho_seqs/actions

Yup! Been going through that, thank you!!!

**Pull request merged**
